@extends('layouts.app')
@section('title', isset($asset) ? 'Ubah Aset Masuk' : 'Catat Aset Masuk')
@section('content')
<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-200/80">
<div class="flex items-center justify-between border-b border-slate-100 pb-3 mb-4"><div class="flex items-center space-x-2"><i class="fa-solid fa-arrow-right-to-bracket text-blue-600"></i><h3 class="font-bold text-slate-800 text-sm uppercase tracking-wider">{{ isset($asset) ? 'Ubah Aset Masuk' : 'Catat Aset Masuk' }}</h3></div><a href="{{ route('transactions.asset.masuk') }}" class="text-xs font-medium text-blue-600 hover:text-blue-800">Lihat daftar penuh</a></div>
<form method="POST" id="assetMasukForm" onsubmit="return stripRupiah()" action="{{ isset($asset) ? route('transactions.asset.masuk.update', $asset) : route('transactions.asset.masuk.store') }}" enctype="multipart/form-data" class="grid grid-cols-1 md:grid-cols-3 gap-4">
@csrf
@if(isset($asset))@method('PUT')@endif
<label class="block text-xs font-bold text-slate-700 uppercase">Tahun Perolehan<select id="procurement_year" name="procurement_year" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500">@for($y = $yearNow; $y >= 1990; $y--)<option value="{{ $y }}" @selected(old('procurement_year', isset($asset) ? $asset->procurement_year : null) == $y)>{{ $y }}</option>@endfor</select></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Tanggal Perolehan<input id="acquisition_date" name="acquisition_date" type="date" value="{{ old('acquisition_date', isset($asset) ? $asset->acquisition_date->format('Y-m-d') : '') }}" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500"></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Jenis Aset<select name="kib_type" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500">@foreach(['A' => 'KIB A – Tanah', 'B' => 'KIB B – Peralatan & Mesin', 'C' => 'KIB C – Gedung & Bangunan', 'D' => 'KIB D – Jalan, Irigasi & Jaringan', 'E' => 'KIB E – Aset Tetap Lainnya'] as $v => $l)<option value="{{ $v }}" @selected(old('kib_type', isset($asset) ? $asset->kib_type : null) === $v)>{{ $l }}</option>@endforeach</select></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Kode Barang<input name="asset_code" value="{{ old('asset_code', isset($asset) ? $asset->asset_code : '') }}" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm font-mono outline-none focus:ring-2 focus:ring-blue-500" placeholder="AST-2026-KIBB-0012"></label>
<label class="block text-xs font-bold text-slate-700 uppercase md:col-span-2">Nama Barang<input name="name" value="{{ old('name', isset($asset) ? $asset->name : '') }}" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500"></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Harga Perolehan (Rp)<input id="acquisition_value" name="acquisition_value" type="text" inputmode="numeric" value="{{ old('acquisition_value', isset($asset) ? $asset->acquisition_value : '') }}" required placeholder="1.000.000" class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500"></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Sumber Dana<select name="funding_source" required class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500">@foreach(['BOS', 'DAK', 'HIBAH', 'Komite'] as $s)<option value="{{ $s }}" @selected(old('funding_source', isset($asset) ? $asset->funding_source : null) === $s)>{{ $s }}</option>@endforeach</select></label>
<label class="block text-xs font-bold text-slate-700 uppercase">Lokasi (opsional)<select name="location_id" class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500"><option value="">—</option>@foreach($locations as $loc)<option value="{{ $loc->id }}" @selected(old('location_id', isset($asset) ? $asset->location_id : null) == $loc->id)>{{ $loc->name }} ({{ $loc->building->name ?? 'Tanpa Gedung' }})</option>@endforeach</select></label>
<label class="block text-xs font-bold text-slate-700 uppercase md:col-span-3">Bukti Belanja (nota/kwitansi/BAST, gambar/PDF, maks 500KB)<input name="proof" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" class="mt-1 w-full bg-slate-50 border border-slate-300 rounded-xl p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-500 file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:bg-blue-600 file:text-white file:text-xs file:font-medium hover:file:bg-blue-700"></label>
<div class="md:col-span-3 flex items-center gap-2"><button class="inline-flex items-center px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium transition"><i class="fa-solid fa-floppy-disk mr-2"></i> {{ isset($asset) ? 'Update' : 'Simpan' }}</button>@if(isset($asset))<a href="{{ route('transactions.asset.masuk.create') }}" class="inline-flex items-center px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-sm font-medium transition">Batal</a>@endif</div>
</form>
</div>
<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-200/80 overflow-x-auto"><h4 class="font-bold text-slate-800 text-sm uppercase tracking-wider mb-3">Hasil Input</h4><table id="assetMasukTable" class="w-full text-sm">
<thead><tr class="border-b-2 border-slate-200 text-slate-500 text-xs uppercase"><th class="px-4 py-3 text-left">Tanggal</th><th class="px-4 py-3 text-left">Jenis / Kode</th><th class="px-4 py-3 text-left">Nama</th><th class="px-4 py-3 text-right">Harga</th><th class="px-4 py-3 text-left">Dana</th><th class="px-4 py-3 text-center">Bukti</th><th class="px-4 py-3 text-center">Aksi</th></tr></thead>
<tbody>@forelse($assets as $a)<tr class="border-b border-slate-100 hover:bg-slate-50"><td class="px-4 py-3">{{ $a->acquisition_date->format('d-m-Y') }}</td><td class="px-4 py-3"><span class="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-medium bg-blue-100 text-blue-800">KIB {{ $a->kib_type }}</span><div class="font-mono text-xs font-bold text-blue-600 mt-1">{{ $a->asset_code }}</div></td><td class="px-4 py-3 font-semibold">{{ $a->name }}</td><td class="px-4 py-3 text-right">Rp {{ number_format($a->acquisition_value, 0, ',', '.') }}</td><td class="px-4 py-3">{{ $a->funding_source ?? '-' }}</td><td class="px-4 py-3 text-center">@if($a->proof_path)<button type="button" onclick="openProof('{{ asset('storage/'.$a->proof_path) }}', '{{ strtolower(pathinfo($a->proof_path, PATHINFO_EXTENSION)) === 'pdf' ? 'pdf' : 'img' }}')" class="text-blue-600 hover:text-blue-800" title="Lihat bukti"><i class="fa-solid fa-file-lines"></i></button>@else<span class="text-slate-300">-</span>@endif</td><td class="px-4 py-3 text-center whitespace-nowrap"><a href="{{ route('transactions.asset.masuk.edit', $a) }}" class="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-amber-100 text-amber-700 hover:bg-amber-200" title="Ubah"><i class="fa-solid fa-pencil text-xs"></i></a><form method="POST" action="{{ route('transactions.asset.masuk.destroy', $a) }}" class="inline" onsubmit="return confirmDelete(event, this)">@csrf @method('DELETE')<button class="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-red-100 text-red-700 hover:bg-red-200 ml-1" title="Hapus"><i class="fa-solid fa-trash text-xs"></i></button></form></td></tr>@empty<tr><td colspan="7" class="px-4 py-6 text-center text-slate-500">Belum ada data.</td></tr>@endforelse</tbody>
</table></div>
<script>
const py = document.getElementById('procurement_year'), ad = document.getElementById('acquisition_date');
py.addEventListener('change', () => { if (!ad.value || !ad.value.startsWith(py.value)) ad.value = py.value + (ad.value ? ad.value.slice(4) : '-01-01'); });
ad.addEventListener('change', () => { if (ad.value) py.value = ad.value.slice(0, 4); });
const rp = document.getElementById('acquisition_value');
const fmtRp = v => v.replace(/\D/g, '').replace(/\B(?=(\d{3})+(?!\d))/g, '.');
if (rp) { if (rp.value) rp.value = fmtRp(rp.value); rp.addEventListener('input', () => { rp.value = fmtRp(rp.value); }); }
function stripRupiah() { if (rp) rp.value = rp.value.replace(/\./g, ''); return true; }
function openProof(url, kind) { const lb = document.getElementById('proofLightbox'), im = document.getElementById('proofImg'), fr = document.getElementById('proofFrame'); im.classList.add('hidden'); fr.classList.add('hidden'); if (kind === 'pdf') { fr.src = url; fr.classList.remove('hidden'); } else { im.src = url; im.classList.remove('hidden'); } lb.classList.remove('hidden'); document.body.style.overflow = 'hidden'; }
function closeProof() { const lb = document.getElementById('proofLightbox'), im = document.getElementById('proofImg'), fr = document.getElementById('proofFrame'); lb.classList.add('hidden'); im.src = ''; fr.src = ''; document.body.style.overflow = ''; }
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeProof(); });
</script>
<div id="proofLightbox" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onclick="if(event.target===this)closeProof()"><div class="bg-white rounded-2xl shadow-xl w-[75vw] h-[75vh] max-w-[75vw] max-h-[75vh] flex flex-col overflow-hidden"><div class="flex items-center justify-between px-4 py-2 border-b border-slate-200"><span class="text-xs font-bold uppercase tracking-wider text-slate-600">Bukti Belanja</span><button type="button" onclick="closeProof()" class="text-slate-500 hover:text-red-600 text-lg leading-none">&times;</button></div><div class="flex-1 min-h-0"><img id="proofImg" class="hidden w-full h-full object-contain bg-slate-50" alt="Bukti"><iframe id="proofFrame" class="hidden w-full h-full bg-white" title="Bukti PDF"></iframe></div></div></div>
@endsection
@section('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
(function ($) { $(function () { $('#assetMasukTable').DataTable({ searching: true, paging: true, info: true, lengthChange: true, pageLength: 10, lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'Semua']], columnDefs: [{ targets: -1, orderable: false, searchable: false }], language: { url: 'https://cdn.datatables.net/plug-ins/1.13.8/i18n/id.json' } }); }); })(jQuery);
function confirmDelete(e, f) { e.preventDefault(); Swal.fire({ title: 'Hapus aset?', text: 'Data terhapus permanen.', icon: 'warning', showCancelButton: true, confirmButtonColor: '#dc2626', confirmButtonText: 'Ya, hapus', cancelButtonText: 'Batal' }).then(r => { if (r.isConfirmed) f.submit(); }); return false; }
</script>
@endsection
